#... (all other services)
  dashboard-service:
    build: ./services/dashboard-service
    ports:
      - "3001:3001"
    depends_on:
      - agent-monitoring-service
    networks:
      - job-agent-net
    restart: unless-stopped
#...