version: '3.8'

services:
  # Agent Orchestrator Service (Main API)
  agent-orchestrator:
    build: ./services/agent-orchestrator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/agent-orchestrator:/app
      - /app/node_modules
    depends_on:
      - llm-service
      - agent-monitoring-service
    networks:
      - job-agent-net
    restart: unless-stopped

  # LLM Service (AI/ML Processing)
  llm-service:
    build: ./services/llm-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/llm-service:/app
    networks:
      - job-agent-net
    restart: unless-stopped

  # Dashboard Service (Frontend)
  dashboard-service:
    build: ./services/dashboard-service
    ports:
      - "3001:3001"
    depends_on:
      - agent-orchestrator
    networks:
      - job-agent-net
    restart: unless-stopped

  # Agent Monitoring Service
  agent-monitoring-service:
    build: ./services/agent-monitoring-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./services/agent-monitoring-service:/app
    networks:
      - job-agent-net
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jobagent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - job-agent-net
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - job-agent-net
    restart: unless-stopped

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - job-agent-net
    restart: unless-stopped

networks:
  job-agent-net:
    driver: bridge

volumes:
  postgres_data:
