version: '3.8'

# Override file for development - use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development overrides
  llm-service:
    build:
      target: builder  # Use builder stage for development
    volumes:
      - ./services/llm-service:/usr/src/app
    environment:
      - PYTHONPATH=/usr/src/app
      - RELOAD=true
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  agent-orchestrator:
    volumes:
      - ./services/agent-orchestrator:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  dashboard-service:
    build:
      target: deps  # Use deps stage for development
    volumes:
      - ./services/dashboard-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: ["npm", "run", "dev"]

  agent-monitoring-service:
    volumes:
      - ./services/agent-monitoring-service:/usr/src/app
    environment:
      - PYTHONPATH=/usr/src/app
      - LOG_LEVEL=debug
    command: ["python", "-u", "app/worker.py"]

  # Remove nginx in development
  nginx:
    profiles:
      - production