import { EmailService } from '../services/email.service';
import dotenv from 'dotenv';

dotenv.config();

interface DailyReportData {
  date: string;
  applicationsSubmitted: number;
  outreachSent: number;
  responsesReceived: number;
  newJobsFound: number;
  platformStats: {
    linkedin: number;
    wellfound: number;
    glassdoor: number;
  };
}

class DailyReportGenerator {
  private emailService: EmailService;
  private recipientEmail: string;

  constructor() {
    this.emailService = new EmailService();
    this.recipientEmail = process.env.SMTP_TO || '';
  }

  private async getDailyData(): Promise<DailyReportData> {
    // Use deterministic mock data if USE_MOCK_DATA env var is set to 'true', otherwise fetch from database
    const today = new Date().toISOString().split('T')[0];
    const useMockData = process.env.USE_MOCK_DATA === 'true';
    
    if (useMockData) {
      // Deterministic mock data for development/testing
      return {
        date: today,
        applicationsSubmitted: 7,
        outreachSent: 12,
        responsesReceived: 2,
        newJobsFound: 18,
        platformStats: {
          linkedin: 5,
          wellfound: 3,
          glassdoor: 2
        }
      };
    }
    // TODO: Implement actual database queries for production use
    // For now, throw an error to prevent accidental use in production
    throw new Error('getDailyData: Real data fetching not implemented. Set USE_MOCK_DATA=true for mock data.');
  }

  private generateEmailHTML(data: DailyReportData): string {
    return `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #2c3e50; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .stat-card { 
            display: inline-block; 
            margin: 10px; 
            padding: 15px; 
            background-color: #f8f9fa; 
            border-radius: 8px; 
            border-left: 4px solid #3498db;
            min-width: 200px;
        }
        .stat-number { font-size: 24px; font-weight: bold; color: #2c3e50; }
        .stat-label { color: #7f8c8d; text-transform: uppercase; font-size: 12px; }
        .platform-stats { margin-top: 20px; }
        .platform-item { 
            padding: 8px 0; 
            border-bottom: 1px solid #eee; 
            display: flex; 
            justify-content: space-between; 
        }
        .footer { 
            margin-top: 30px; 
            padding-top: 20px; 
            border-top: 1px solid #eee; 
            color: #7f8c8d; 
            font-size: 12px; 
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎯 Daily Job Application Report</h1>
        <p>Report for ${data.date}</p>
    </div>
    
    <div class="content">
        <h2>📊 Today's Summary</h2>
        
        <div class="stat-card">
            <div class="stat-number">${data.applicationsSubmitted}</div>
            <div class="stat-label">Applications Submitted</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-number">${data.outreachSent}</div>
            <div class="stat-label">Outreach Messages Sent</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-number">${data.responsesReceived}</div>
            <div class="stat-label">Responses Received</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-number">${data.newJobsFound}</div>
            <div class="stat-label">New Jobs Found</div>
        </div>
        
        <div class="platform-stats">
            <h3>📱 Platform Breakdown</h3>
            <div class="platform-item">
                <span>LinkedIn</span>
                <span><strong>${data.platformStats.linkedin}</strong> applications</span>
            </div>
            <div class="platform-item">
                <span>Wellfound (AngelList)</span>
                <span><strong>${data.platformStats.wellfound}</strong> applications</span>
            </div>
            <div class="platform-item">
                <span>Glassdoor</span>
                <span><strong>${data.platformStats.glassdoor}</strong> applications</span>
            </div>
        </div>
        
        <div class="footer">
            <p>This is an automated report generated by AJOB4AGENT.</p>
            <p>Generated at: ${new Date().toISOString()}</p>
        </div>
    </div>
</body>
</html>`;
  }

  async generateAndSend(): Promise<void> {
    try {
      // Verify email configuration
      const isConnected = await this.emailService.verifyConnection();
      if (!isConnected) {
        throw new Error('Failed to connect to SMTP server');
      }

      // Get daily data
      const reportData = await this.getDailyData();
      
      // Generate email content
      const emailHTML = this.generateEmailHTML(reportData);
      
      // Send email
      await this.emailService.sendEmail({
        to: this.recipientEmail,
        subject: `📊 Daily Job Report - ${reportData.date}`,
        html: emailHTML
      });

      console.log('Daily report sent successfully!');
      
    } catch (error) {
      console.error('Failed to generate and send daily report:', error);
      process.exit(1);
    }
  }
}

// Run the report generator when this file is executed directly
if (require.main === module) {
  const generator = new DailyReportGenerator();
  generator.generateAndSend().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

export default DailyReportGenerator;