global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # AJOB4AGENT Services
  - job_name: 'dashboard-service'
    static_configs:
      - targets: ['dashboard-service:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  - job_name: 'agent-orchestrator'
    static_configs:
      - targets: ['agent-orchestrator:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'llm-service'
    static_configs:
      - targets: ['llm-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'agent-monitoring-service'
    static_configs:
      - targets: ['agent-monitoring-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s